name: Build Globals Dump

on:
  push:

jobs:
  build-server:
    name: Build Server Globals
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Build Server Image
        run: docker build -t globals-server -f docker/server/Dockerfile .
      - name: Build Dump File
        run: docker run globals-server > dump.txt
      - name: Parse Dump File
        run: sudo apt-get install -y python3 && python3 parse.py
