name: Build Globals Dump

on:
  push:

jobs:
  build-server:
    name: Build Server Globals
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Build Globals File
        run: |
          docker build -t globals-server -f docker/server/Dockerfile .
          docker run --name=globals-server-test --mount type=bind,source=./data,target=/home/steam/garrysmod/garrysmod/data globals-server
      - name: Cat File
        run: cat ./data/globals-dump.txt
